export const personalInfo = {
  name: 'Pavan Sekhar Mandavilli',
  shortName: 'Pavan Sekhar',
  title: 'AI Engineer',
  roles: ['AI Engineer', 'ML Developer', 'Backend Developer', 'Deep Learning Enthusiast', 'Problem Solver'],
  email: 'pavanmandavilli24@gmail.com',
  phone: '+91 8074984348',
  location: 'Bengaluru, India',
  birthday: 'January 24, 2004',
  bio: 'Aspiring TensorFlow Developer with a strong foundation in AI, Machine Learning, and backend development. I transform complex data into intelligent solutions — from computer vision systems to scalable APIs. Passionate about driving innovation at the intersection of deep learning and real-world applications.',
  social: {
    linkedin: 'https://linkedin.com/in/pavan-sekhar-mandavilli/',
    github: 'https://github.com/Pavanmandavilli',
    instagram: 'https://instagram.com/chocolate_boy__485/',
    resume: 'https://drive.google.com/file/d/1eKQvDGTBtmd9lYvfs4KjwICalw-vpABf/view?usp=sharing'
  },
};

export const stats = [
  { value: 1.7, suffix: '+', label: 'Years Experience' },
  { value: 8, suffix: '+', label: 'Projects Built' },
  { value: 2, suffix: '', label: 'Certifications' },
  { value: 95, suffix: '%', label: 'Python Proficiency' },
];

export const skillCategories = [
  {
    id: 'programming',
    label: 'Programming',
    icon: '💻',
    color: '#00ff88',
    skills: [
      { name: 'Python',  level: 95 },
      { name: 'SQL',     level: 80 },
      { name: 'Java',    level: 65 },
      { name: 'C',       level: 60 },
    ],
  },
  {
    id: 'ml-ai',
    label: 'ML & AI',
    icon: '🧠',
    color: '#00f5ff',
    skills: [
      { name: 'Deep Learning',        level: 88 },
      { name: 'LLMs',                 level: 87 },
      { name: 'RAG',                  level: 85 },
      { name: 'Computer Vision',      level: 85 },
      { name: 'Anomaly Detection',    level: 85 },
      { name: 'Real-Time Inference',  level: 83 },
      { name: 'NLP',                  level: 82 },
      { name: 'Model Fine-tuning',    level: 80 },
      { name: 'Feature Engineering',  level: 80 },
      { name: 'Hyperparameter Tuning',level: 78 },
    ],
  },
  {
    id: 'frameworks',
    label: 'ML Frameworks',
    icon: '⚙️',
    color: '#7b2ff7',
    skills: [
      { name: 'TensorFlow',        level: 90 },
      { name: 'Scikit-Learn',      level: 85 },
      { name: 'PyTorch',           level: 82 },
      { name: 'Keras',             level: 82 },
      { name: 'Hugging Face',      level: 80 },
      { name: 'OpenCV',            level: 78 },
    ],
  },
  {
    id: 'llm',
    label: 'LLM & Agents',
    icon: '🤖',
    color: '#ff006e',
    skills: [
      { name: 'Prompt Engineering', level: 87 },
      { name: 'LangChain',          level: 83 },
      { name: 'MCP',                level: 80 },
      { name: 'LangGraph',          level: 76 },
    ],
  },
  {
    id: 'data',
    label: 'Data Pipeline',
    icon: '📊',
    color: '#ffc864',
    skills: [
      { name: 'NumPy',              level: 88 },
      { name: 'Pandas',             level: 88 },
      { name: 'Data Preprocessing', level: 85 },
      { name: 'Matplotlib',         level: 80 },
      { name: 'Seaborn',            level: 75 },
      { name: 'Redis',              level: 75 },
      { name: 'Kafka Streaming',    level: 65 },
    ],
  },
  {
    id: 'vector-db',
    label: 'Vector DBs',
    icon: '🗄️',
    color: '#b4b4ff',
    skills: [
      { name: 'ChromaDB', level: 76 },
      { name: 'MilvusDB', level: 75 },
      { name: 'Pinecone', level: 72 },
      { name: 'FAISS',    level: 72 },
    ],
  },
  {
    id: 'backend',
    label: 'Backend & APIs',
    icon: '🔧',
    color: '#38bdf8',
    skills: [
      { name: 'FastAPI',       level: 88 },
      { name: 'REST API Design',level: 86 },
      { name: 'Spring Boot',   level: 80 },
      { name: 'PostgreSQL',    level: 78 },
      { name: 'MongoDB',       level: 78 },
      { name: 'Flask',         level: 75 },
      { name: 'MySQL',         level: 72 },
    ],
  },
  {
    id: 'cloud',
    label: 'Cloud & DevOps',
    icon: '☁️',
    color: '#34d399',
    skills: [
      { name: 'Git/GitHub',       level: 88 },
      { name: 'Model Deployment', level: 80 },
      { name: 'Docker',           level: 72 },
      { name: 'GCP',              level: 62 },
    ],
  },
  {
    id: 'Frontend',
    label: 'Frontend Development',
    icon: '💻',
    color: '#00ff88',
    skills: [
      { name: 'React',            level: 85 },
      { name: 'JavaScript',       level: 90 },
      { name: 'HTML/CSS',         level: 88 },
    ],
  },
];

export const experience = [
  {
    title: 'Software Development Engineer',
    company: 'Kapture CX',
    location: 'Bengaluru, India',
    period: '2024 — Present',
    description: 'Develops scalable backend solutions using microservices and cloud technologies. Works on AI-powered customer experience platforms, integrating machine learning models into production pipelines.',
    tags: ['Python', 'Microservices', 'Cloud', 'API Development', 'AI Integration', 'MultiAgent Systems'],
    current: true,
  },
  {
    title: 'Director of Technology',
    company: 'Kognitiv Technology Club, KL University',
    location: 'Vijayawada, India',
    period: '2023 — 2024',
    description: 'Led technology initiatives and conducted AI/ML sessions for 100+ students. Managed industry-related projects and mentored junior members in machine learning and computer vision.',
    tags: ['AI/ML', 'Leadership', 'Teaching', 'Computer Vision', 'Project Management'],
    current: false,
  },
];

export const projects = [
  {
    name: 'GearUp & GO',
    description: 'A full-stack web application for vehicle rental and management. Features real-time availability tracking, user authentication, and payment integration.',
    category: 'Web Development',
    tags: ['Django', 'Python', 'MySQL', 'HTML/CSS', 'JavaScript'],
    gradient: 'linear-gradient(135deg, #00f5ff22, #7b2ff722)',
    accent: '#00f5ff',
  },
  {
    name: 'Genius Gauge',
    description: 'An intelligent assessment application powered by NLP and machine learning. Generates adaptive tests and provides detailed performance analytics.',
    category: 'AI Application',
    tags: ['Python', 'NLP', 'Machine Learning', 'TensorFlow'],
    gradient: 'linear-gradient(135deg, #7b2ff722, #ff006e22)',
    accent: '#7b2ff7',
  },
  {
    name: 'GeoLens',
    description: 'Computer vision application for geographic feature detection and satellite image analysis using deep learning models and OpenCV.',
    category: 'Computer Vision',
    tags: ['Computer Vision', 'OpenCV', 'Deep Learning', 'Python'],
    gradient: 'linear-gradient(135deg, #00ff8822, #00f5ff22)',
    accent: '#00ff88',
  },
  {
    name: 'OCR Conversion (GPU→CPU)',
    description: 'Optimized OCR pipeline migrating GPU-dependent models to CPU inference with minimal accuracy loss. Achieved 3x cost reduction in cloud deployments.',
    category: 'AI/ML Optimization',
    tags: ['OCR', 'PyTorch', 'Model Optimization', 'TensorFlow'],
    gradient: 'linear-gradient(135deg, #ff006e22, #7b2ff722)',
    accent: '#ff006e',
  },
  {
    name: 'Telegram SecureCam',
    description: 'Automated security camera monitoring system integrated with Telegram Bot API. Sends real-time alerts with AI-powered motion detection.',
    category: 'IoT & AI',
    tags: ['Python', 'Computer Vision', 'Telegram API', 'OpenCV'],
    gradient: 'linear-gradient(135deg, #00f5ff22, #00ff8822)',
    accent: '#00f5ff',
  },
  {
    name: 'Mood Monitor',
    description: 'Real-time emotion detection application using facial recognition and deep learning. Analyzes facial expressions to classify emotional states with high accuracy.',
    category: 'Computer Vision',
    tags: ['Deep Learning', 'Computer Vision', 'TensorFlow', 'OpenCV'],
    gradient: 'linear-gradient(135deg, #7b2ff722, #00f5ff22)',
    accent: '#7b2ff7',
  },
  {
    name: 'BlogForge',
    description: 'AI-assisted blogging platform with automated content suggestions and SEO optimization powered by language models.',
    category: 'Web + AI',
    tags: ['Django', 'LangChain', 'Python', 'LLM', 'MySQL'],
    gradient: 'linear-gradient(135deg, #ff006e22, #00f5ff22)',
    accent: '#ff006e',
  },
  {
    name: 'Doc Mania',
    description: 'Intelligent document processing and Q&A system using RAG (Retrieval-Augmented Generation) architecture for document understanding.',
    category: 'AI Application',
    tags: ['LangChain', 'RAG', 'Python', 'Vector DB', 'LLM'],
    gradient: 'linear-gradient(135deg, #00ff8822, #7b2ff722)',
    accent: '#00ff88',
  },
  {
    name: 'CloudMCP Gateway',
    description: 'Production-grade MCP server hosted on GCP that lets users register and deploy custom tools tied to their login. Any MCP-compatible client — Claude Desktop, Cursor, or custom agents — can connect and invoke tools over the standard protocol, with per-user isolation and live tool discovery.',
    category: 'MCP & Cloud Infra',
    tags: ['MCP', 'GCP', 'FastAPI', 'Python', 'OAuth2', 'Cloud Run'],
    gradient: 'linear-gradient(135deg, #ffc86422, #34d39922)',
    accent: '#ffc864',
  },
  {
    name: 'AgentForge',
    description: 'Visual multi-agent builder powered by LangGraph. Users compose agents via dropdown UI — select agent type, bind GCP-persisted tools, and wire inter-agent edges. The resulting graph is serialised, stored in GCP, and executed serverlessly with full state checkpointing and real-time streaming output.',
    category: 'Multi-Agent Systems',
    tags: ['LangGraph', 'GCP', 'LangChain', 'Python', 'Cloud Run', 'Pub/Sub'],
    gradient: 'linear-gradient(135deg, #b4b4ff22, #ff006e22)',
    accent: '#b4b4ff',
  },
];

export const education = [
  {
    degree: 'B.Tech in Artificial Intelligence',
    institution: 'K L University',
    location: 'Vijayawada, India',
    period: '2021 — 2025',
    gpa: null,
    icon: '🎓',
  },
  {
    degree: 'Board of Intermediate (MPC)',
    institution: 'Sri Chaitanya Junior College',
    location: 'Kakinada, India',
    period: '2019 — 2021',
    gpa: null,
    icon: '📚',
  },
  {
    degree: 'Board of Secondary School',
    institution: 'Margadarsi High School',
    location: 'Tallarevu, India',
    period: '2018 — 2019',
    gpa: null,
    icon: '🏫',
  },
];

export const certifications = [
  { name: 'TensorFlow Developer', issuer: 'Google', icon: '🧠' },
  { name: 'Python for Data Science', issuer: 'IBM', icon: '🐍' },
];
